### ISSUE TITLE
缺少wx.ready方法

### ISSUE THREAD

**Issue by DestinyZxw** [beeven/rx-jweixin#1]
最新jssdk微信文档中提到，调用前需要按接口文档 描述在方法中调用，这不会带来问题么？

**Comment by beeven** [comment]
jssdk中是先调用wx.config同步方法，然后再等待wx.ready事件和wx.error事件。这里把整个过程打包一起了，也就是使用config返回一个observable，当有wx.ready或者wx.error，这个observable就会有输出。
具体可以参考test。

**Comment by DestinyZxw** [comment]
抱歉现在才看到您的回复，现在我就是遇到了微信sdk人身核验接口ios回调无响应的异常（安卓ok），不知和您当时遇到的是同一个问题，项目也是使用的ng+rxjs，已经和微信那边的工作人员上报过，仍未解决
